# Generated by Django 2.0.1 on 2018-01-28 13:15

import back.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('position', models.CharField(blank=True, max_length=122, null=True, verbose_name='Должность')),
                ('uuid', models.CharField(default=back.profiles.models.get_default_uuid, editable=False, max_length=32, unique=True, verbose_name='UUID')),
                ('email', models.EmailField(max_length=125, unique=True, verbose_name='Имейл')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ф.И.О.')),
                ('bio', models.TextField(blank=True, max_length=300, null=True, verbose_name='О пользователе')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('accepted_tos', models.BooleanField(verbose_name='Принято соглашение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_mobile', models.CharField(blank=True, max_length=26, null=True, verbose_name='Мобильный тел.')),
                ('phone_small', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Короткий номер')),
                ('phone_city', models.PositiveIntegerField(blank=True, null=True, verbose_name='Городской номер')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
    ]
