# Generated by Django 2.0.1 on 2018-02-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/media/default.jpg', null=True, upload_to='avatars/', verbose_name='Изображение'),
        ),
    ]
